services:
  db_postgres_drivenops:
    image: postgres
    container_name: db_postgres_drivenops
    restart: always
    ports:
      - 1122:5432
    env_file:
      - .env
    volumes:
      - pg_drivenops:/var/lib/postgresql/data

  node_drivenops:
    container_name: node_drivenops
    build: ./back-end
    ports:
      - 5000:5000
    depends_on:
      - db_postgres_drivenops
    env_file:
      - .env

  react_drivenops:
    container_name: react_drivenops
    build: ./front-end
    volumes:
      - build_react:/var/www/html

volumes:
  pg_drivenops:
  build_react: