name: PullRequest
on: [pull_request]
jobs:
  PullRequest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Create env file
        uses: SpicyPizza/create-envfile@v1
        with:
          envkey_DATABASE_URL: ${{secrets.POSTGRES_URL_TEST}}
          envkey_POSTGRES_USER: ${{secrets.POSTGRES_USER}}
          envkey_POSTGRES_PASSWORD: ${{secrets.POSTGRES_PASSSWORD}}
          envkey_POSTGRES_DB: ${{secrets.POSTGRES_DB_TEST}}
          file_name: .env.test
      - name: Run tests
        run: docker-compose -f docker-compose-test.yaml run node_drivenops npm run test
      - name: Build
        run: npm i && npm run build
